CREATE TABLE users (
  id TEXT PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  profile_pic TEXT NOT NULL
);

CREATE TABLE saves (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  save_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  save_data TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (id)
);